//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRInovatec
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Document
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string DocumentText { get; set; }
        public string DocumentType { get; set; }
        public bool DocumentLock { get; set; }
        public Nullable<int> Owner { get; set; }
        public int Uploader { get; set; }
        public string Language { get; set; }
        public string Virtual_Path { get; set; }
    
        public virtual User User1 { get; set; }
    }
}
